# Railway Nixpacks Configuration - Force Python Detection
# This file overrides Railway's automatic language detection

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Python FastAPI build complete'"]

[start]
cmd = "python main.py"