# TaxPoynt Platform Railway Configuration
# Simplified for reliable deployment

[build]
builder = "nixpacks"

[deploy]
# Simplified start command for Railway
startCommand = "cd platform/backend && uvicorn main:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips '*' --log-level info"

# Health check configuration 
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE" 
restartPolicyMaxRetries = 3

# Environment variables
[variables]
ENVIRONMENT = "production"
PYTHONPATH = "/app/platform/backend:/app"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"