# TaxPoynt Platform Railway Configuration
# Multi-service deployment for enterprise architecture

[build]
builder = "nixpacks"

[deploy]
startCommand = "cd platform/backend && uvicorn main:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips '*'"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE" 
restartPolicyMaxRetries = 5

# Environment-specific variables will be set in Railway dashboard
[variables]
ENVIRONMENT = "production"
DATABASE_URL = "$DATABASE_URL"
REDIS_URL = "$REDIS_URL"