# TaxPoynt Platform Railway Configuration
# Simplified for reliable deployment

[build]

[deploy]
# Direct start command - use 'python' instead of 'python3' for Railway
startCommand = "cd platform/backend && python -m pip install -r requirements.txt && python -m uvicorn main:app --host 0.0.0.0 --port $PORT --proxy-headers --forwarded-allow-ips '*' --log-level info"

# Health check configuration 
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE" 
restartPolicyMaxRetries = 3

# Environment variables
[variables]
ENVIRONMENT = "production"
PYTHONPATH = "/app/platform/backend:/app"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"