# TaxPoynt Platform Railway Configuration
# Python FastAPI deployment

[build]

[deploy]
# Use root-level main.py for Railway Python detection
startCommand = "python main.py"

# Health check configuration 
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE" 
restartPolicyMaxRetries = 3

# Environment variables
[variables]
ENVIRONMENT = "production"
PYTHONPATH = "/app/platform/backend:/app"
PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"