name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: Unit Tests (Python 3.11)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      ENVIRONMENT: development
      PYTHONPATH: platform/backend
      # Router validation modes for CI
      ROUTER_STRICT_OPS: "true"
      ROUTER_VALIDATE_ON_STARTUP: "true"
      ROUTER_FAIL_FAST_ON_STARTUP: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: |
            platform/backend/requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r platform/backend/requirements.txt

      - name: Run unit tests
        run: |
          pytest -q platform/tests/unit
